name: visibilitycheck

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8089:80"
    depends_on:
      - backend
    networks:
      - vcnet

  backend:
    image: php:8.2-apache
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    volumes:
      - ./backend:/var/www/html/:rw
      - ./backend/docker/apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - mariadb
    networks:
      - vcnet

  mariadb:
    image: mariadb:12.0.2-noble
    ports:
      - "3366:3306" # expose for debugging
    volumes:
      - ./backend/docker/mariadb:/docker-entrypoint-initdb.d/:ro
    environment:
      MARIADB_DATABASE: visibilitycheck
      MARIADB_USER: visibility
      MARIADB_PASSWORD: m1PM2PRaJx
      MARIADB_ROOT_PASSWORD: g8whwXJJVJ
    networks:
      - vcnet

networks:
  vcnet:
    driver: bridge