ServerName visibilitycheck

<VirtualHost *:8080>
  DocumentRoot "/var/www/html/visibilitycheck/docs"
  RequestReadTimeout header=20-40,minrate=500
  RequestReadTimeout body=10,minrate=500
  Header set X-Frame-Options "DENY"
  <Directory "/var/www/html/visibilitycheck/docs">
    Options FollowSymlinks
    AllowOverride ALL
    Require all granted
    DirectoryIndex index.html
    # Rewrite rules
    RewriteEngine On
  </Directory>

</VirtualHost>
