ServerName Backend

<VirtualHost *:80>
  DocumentRoot "/var/www/html/public"

  <Directory "/var/www/html/public">
    Options FollowSymlinks
    AllowOverride ALL
    Require all granted
    DirectoryIndex index.php index.html
    # Rewrite rules
    RewriteEngine On
  </Directory>

</VirtualHost>
